config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "kayaks#index"

  resources :kayaks do
    resources :bookings, only: %i(new create edit update)
  end
  resources :bookings, only: :destroy do
    member do
      patch "accept"
      patch "decline"
    end
  end

  get "/dashboard", to: "pages#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :kayak

  validates :status, :total_price, :start_date, :end_date, presence: true
end

app/models/kayak.rb
class Kayak < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  CATEGORIES = ["Sea", "River"]

  validates :price_per_day, :adress, :description, :category, :places, :length, :width, presence: true

  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :kayaks
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:edit, :update, :destroy]

  def new
    @kayak = Kayak.find(params[:kayak_id])
    @booking = Booking.new
  end

  def create
    user = current_user
    kayak = Kayak.find(params[:kayak_id])
    @booking = Booking.new(booking_params)
    @booking.user = user
    @booking.kayak = kayak
    @booking.status = "Pending"
    start_date = params[:booking][:start_date].split(" to ").first.to_date.mjd
    end_date = params[:booking][:end_date].to_date.mjd
    total_days = end_date - start_date
    total_price = total_days * kayak.price_per_day
    @booking.total_price = total_price
    if @booking.save!
      redirect_to dashboard_path
    else
      render 'new'
    end
  end

  def edit
    @booking.edit
  end

  def update
    @booking.update!(booking_params)
    redirect_to booking_path(@booking)
  end

  def destroy
    @booking.destroy
    redirect_to dashboard_path
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.status = "Accepted"
    @booking.save!
    redirect_to dashboard_path
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.status = "Declined"
    @booking.save!
    redirect_to dashboard_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:status, :total_price, :kayak_id, :user_id, :start_date, :end_date)
  end
end

app/controllers/kayaks_controller.rb
class KayaksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]
  before_action :set_kayak, only: [:edit, :update, :destroy, :show]

  def index
    @kayaks = Kayak.all
  end

  def new
    @kayak = Kayak.new
  end

  def create
    @kayak = Kayak.new(kayak_params)
    user = current_user
    @kayak.user = user
    if @kayak.save!
      redirect_to kayak_path(@kayak)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @kayak.update(kayak_params)
    redirect_to kayak_path(@kayak)
  end

  def show
  end

  def destroy
    @kayak.destroy
    redirect_to kayaks_path
  end

  private

  def set_kayak
    @kayak = Kayak.find(params[:id])
  end

  def kayak_params
    params.require(:kayak).permit(:id, :description, :price_per_day, :adress, :places, :color, :category, :length, :width, :buoy, :photo)
  end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
    @user = current_user
    @user_kayaks = Kayak.where(user_id: @user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<h1>Book your kayak here</h1>

<div class="container">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <%= simple_form_for [@kayak, @booking] do |f| %>
      <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker", id: "range_start"} %>
      <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker", id: "range_end"} %>
      <%= f.button :submit, "Go", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/kayaks/edit.html.erb
<h1>Edit Kayak</h1>

<div class="container">
  <%= simple_form_for(@kayak) do |f| %>
    <%= f.input :price_per_day %>
    <%= f.input :adress %>
    <%= f.input :description %>
    <%= f.input :places %>
    <%= f.input :color %>
    <%= f.input :category, collection: Kayak::CATEGORIES %>
    <%= f.input :length %>
    <%= f.input :width %>
    <%= f.input :buoy %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>

<%= link_to "Back to dashboard", dashboard_path %>

app/views/kayaks/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS19hOLMuv1FQoFuLP37o0KjvXfmDWH2sp6_w&usqp=CAU)">
  ALL KAYAK
</div>
<ul>
<% @kayaks.each do |kayak| %>
<div class="cards">
  <div class="card-category-1">
  <%= link_to kayak_path(kayak) do %>
    <% if kayak.photo.attached? %>
    <%= cl_image_tag kayak.photo.key, height: 200, width: 250, crop: :fill %>
<% end %>

<div class="description">
<li><strong>OWNER:</strong> <%= kayak.user.first_name %></li>
              <li><strong>Address:</strong> <%= kayak.adress %></li>
              <li><strong>Type:</strong> <%= kayak.category %></li>
              <li><strong>Price:</strong> <%= kayak.price_per_day %>€</li>
  </div>
  </div>

<div>
<% end %>
<% end %>
</ul>

app/views/kayaks/new.html.erb
<h1>Formulaire test:</h1>

<div class="container">
  <%= simple_form_for(@kayak) do |f| %>
    <%= f.input :price_per_day %>
    <%= f.input :adress %>
    <%= f.input :description %>
    <%= f.input :places %>
    <%= f.input :color %>
    <%= f.input :category, collection: Kayak::CATEGORIES %>
    <%= f.input :length %>
    <%= f.input :width %>
    <%= f.input :buoy %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/kayaks/show.html.erb
<h1>This is <%= @kayak.user.first_name %>'s kayak </h1>

<div class="container">
  <div class="card-trip">
    <img src="<%= cl_image_path @kayak.photo.key %>" />
    <div class="card-trip-infos">
      <div class="card-description">
        <h2><%= @kayak.category %> kayak, from <%= @kayak.user.first_name %></h2>
        <h2><%= @kayak.adress %></h2>
        <hr>
        <p><%= @kayak.description %></p>
        <p>Width : <%= @kayak.width %></p>
        <p>Length : <%= @kayak.length %></p>
        <p>Color : <%= @kayak.color %></p>
        <p>Buoy : <%= @kayak.buoy == true ? "Yes" : "No" %></p>
        <p>Nb of places :<%= @kayak.places %></p>
      </div>
      <div class="card-bottom">
        <h2 class="card-trip-pricing"><%= @kayak.price_per_day %>€/day</h2>
        <%= link_to "Book now", new_kayak_booking_path(@kayak), class: "btn btn-flat" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kayakbooking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <% if false %>
      <%= render 'shared/flashes' %>
    <% end %>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1><%= @user.first_name %>'s dashboard</h1>

<div>
  <h3>My pending requests</h3>
  <% @user.bookings.each do |booking| %>
    <% if booking.status == "Pending" %>
      <p>You asked <strong><%= booking.kayak.user.first_name %></strong> to rent his kayak</p>
      <p>from <strong><%= booking.start_date.to_date.strftime("%d %B %Y") %></strong> to <strong><%= booking.end_date.to_date.strftime("%d %B %Y") %></strong></p>
      <p>For : <%= booking.total_price %>€</p>
      <p><%= link_to "Cancel my request", booking_path(booking), method: :delete, data: { confirm: "Are you sure" } %></p>
    <% end %>
  <% end %>

  <h3>My accepted requests</h3>
  <% @user.bookings.each do |booking| %>
    <% if booking.status == "Accepted" %>
      <p><strong><%= booking.kayak.user.first_name %></strong>'s' kayak</p>
      <p>from <strong><%= booking.start_date.to_date.strftime("%d %B %Y") %></strong> to <strong><%= booking.end_date.to_date.strftime("%d %B %Y") %></strong></p>
      <p>For : <%= booking.total_price %>€</p>
    <% end %>
  <% end %>
</div>

<div>
  <h3>Request for my kayaks</h3>
  <% @user.kayaks.each do |kayak| %>
    <% if kayak.bookings.present? %>
      <% kayak.bookings.each do |booking| %>
        <% if booking.status == "Pending" %>
          <p>Asked by <%= booking.user.first_name %></p>
          <p>from <strong><%= booking.start_date.to_date.strftime("%d %B %Y") %></strong> to <strong><%= booking.end_date.to_date.strftime("%d %B %Y") %></strong></p>
          <p>For : <%= booking.total_price %>€</p>
          <%= link_to "Accept this request", accept_booking_path(booking), method: :patch %>
          <%= link_to "Decline this request", decline_booking_path(booking), method: :patch %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

<div>
  <h3>My kayaks</h3>
  <div class="container">
    <% @user_kayaks.each do |kayak| %>
      <div class="card-product">
        <%= cl_image_tag kayak.photo.key %>
        <div class="card-product-infos">
          <p><%= kayak.description %></p>
          <p><%= kayak.price_per_day %></p>
        </div>
        <%= link_to "Edit", edit_kayak_path(kayak) %>
        <%= link_to "Remove", kayak_path(kayak), method: :delete, data: { confirm: "Are you sure ?" } %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <%= image_tag "kayak_booking_logo.png" %>
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "My dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add a kayak", new_kayak_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <% if current_user.nil? %>
              <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
            <% else %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            <% end %>
          </li>
      </ul>
    </div>
  </div>
</div>